-- AlterTable
ALTER TABLE `pdr` MODIFY `overallStatus` ENUM('CREATED_BY_HR', 'EMPLOYEE_FILLING', 'EMPLOYEE_PENDING', 'EMPLOYEE_SUBMITTED_TO_HR', 'HR_REVIEWING_EMPLOYEE', 'HR_REVERTED_TO_EMPLOYEE', 'HR_APPROVED_EMPLOYEE', 'MANAGER_FILLING', 'MANAGER_PENDING', 'MANAGER_SUBMITTED_TO_HR', 'HR_REVIEWING_MANAGER', 'HR_REVERTED_TO_MANAGER', 'HR_APPROVED_MANAGER', 'EMPLOYEE_ACKNOWLEDGING', 'EMPLOYEE_DISAGREED', 'EMPLOYEE_REVERT_TO_MANAGER', 'MANAGER_REVISING', 'EMPLOYEE_ACKNOWLEDGED', 'DIRECTOR_REVIEWING', 'DIRECTOR_REVIEWED', 'COMPLETED') NOT NULL DEFAULT 'CREATED_BY_HR';

-- AlterTable
ALTER TABLE `pdr_comments` MODIFY `commentType` VARCHAR(191) NULL DEFAULT 'GENERAL';

-- AlterTable
ALTER TABLE `pdr_status_transitions` MODIFY `fromStatus` ENUM('CREATED_BY_HR', 'EMPLOYEE_FILLING', 'EMPLOYEE_PENDING', 'EMPLOYEE_SUBMITTED_TO_HR', 'HR_REVIEWING_EMPLOYEE', 'HR_REVERTED_TO_EMPLOYEE', 'HR_APPROVED_EMPLOYEE', 'MANAGER_FILLING', 'MANAGER_PENDING', 'MANAGER_SUBMITTED_TO_HR', 'HR_REVIEWING_MANAGER', 'HR_REVERTED_TO_MANAGER', 'HR_APPROVED_MANAGER', 'EMPLOYEE_ACKNOWLEDGING', 'EMPLOYEE_DISAGREED', 'EMPLOYEE_REVERT_TO_MANAGER', 'MANAGER_REVISING', 'EMPLOYEE_ACKNOWLEDGED', 'DIRECTOR_REVIEWING', 'DIRECTOR_REVIEWED', 'COMPLETED') NOT NULL,
    MODIFY `toStatus` ENUM('CREATED_BY_HR', 'EMPLOYEE_FILLING', 'EMPLOYEE_PENDING', 'EMPLOYEE_SUBMITTED_TO_HR', 'HR_REVIEWING_EMPLOYEE', 'HR_REVERTED_TO_EMPLOYEE', 'HR_APPROVED_EMPLOYEE', 'MANAGER_FILLING', 'MANAGER_PENDING', 'MANAGER_SUBMITTED_TO_HR', 'HR_REVIEWING_MANAGER', 'HR_REVERTED_TO_MANAGER', 'HR_APPROVED_MANAGER', 'EMPLOYEE_ACKNOWLEDGING', 'EMPLOYEE_DISAGREED', 'EMPLOYEE_REVERT_TO_MANAGER', 'MANAGER_REVISING', 'EMPLOYEE_ACKNOWLEDGED', 'DIRECTOR_REVIEWING', 'DIRECTOR_REVIEWED', 'COMPLETED') NOT NULL;

-- AlterTable
ALTER TABLE `users` MODIFY `country` VARCHAR(191) NOT NULL DEFAULT 'Pakistan',
    MODIFY `currency` VARCHAR(191) NOT NULL DEFAULT 'PKR';
