export const EMAIL_EVENTS = {
  PDR_STATUS_NOTIFY: "PDR_STATUS_NOTIFY",
  PDR_EMPLOYEE_PORTAL_CLOSE: "PDR_EMPLOYEE_PORTAL_CLOSE",
  ATTENDANCE_REMINDER: "ATTENDANCE_REMINDER",
  PASSWORD_RESET: "PASSWORD_RESET",
  EVENT_CREATED: "EVENT_CREATED",
  EVENT_REQUIREMENT_NOTIFY: "EVENT_REQUIREMENT_NOTIFY",
  EVENT_CANCELLED: "EVENT_CANCELLED",
};
