// src/constants/email.events.ts
export const EMAIL_EVENTS = {
  PDR_CREATED: "PDR_CREATED",
  PDR_MANAGER_ASSIGNED: "PDR_MANAGER_ASSIGNED",
  PDR_SUBMITTED_HR: "PDR_SUBMITTED_HR",
  PASSWORD_RESET: "PASSWORD_RESET",
};