-- AlterTable
ALTER TABLE `zkteco_attendance_records` MODIFY `overallStatus` ENUM('ON_TIME_ARRIVAL', 'LATE', 'HALF_DAY_LEAVE', 'FULL_DAY_LEAVE_POTENTIAL', 'FULL_DAY_LEAVE', 'EARLY_OUT', 'ON_TIME_LEAVE', 'ABSENT') NULL;
